### ISSUE TITLE
Two unicode character class escapes break the plugin

### ISSUE THREAD

**Issue by lazarljubenovic** [BrainMaestro/eslint-plugin-optimize-regex#85]
Two unicode character class escapes break the plugin.

Source:

```ts
const r = /[\p{P}\p{Z}]/u
```

Error:

```
Oops! Something went wrong! :(

ESLint: 8.29.0

TypeError: Cannot read properties of undefined (reading 'codePoint')
Occurred while linting /home/.../test.ts:1
Rule: "optimize-regex/optimize-regex"
    at getSortValue (/home/.../node_modules/regexp-tree/dist/optimizer/transforms/char-class-classranges-merge-transform.js:103:26)
    at sortCharClass (/home/.../node_modules/regexp-tree/dist/optimizer/transforms/char-class-classranges-merge-transform.js:63:16)
    at Array.sort (<anonymous>)
    at Object.CharacterClass (/home/.../node_modules/regexp-tree/dist/optimizer/transforms/char-class-classranges-merge-transform.js:35:17)
    at pre (/home/.../node_modules/regexp-tree/dist/traverse/index.js:218:55)
    at visit (/home/.../node_modules/regexp-tree/dist/traverse/index.js:41:13)
    at visit (/home/.../node_modules/regexp-tree/dist/traverse/index.js:88:15)
    at astTraverse (/home/.../node_modules/regexp-tree/dist/traverse/index.js:99:3)
    at Object.traverse (/home/.../node_modules/regexp-tree/dist/traverse/index.js:172:5)
    at Object.transform (/home/.../node_modules/regexp-tree/dist/transform/index.js:134:14)
```

**Comment by diegocr** [comment]
Any update on this, @BrainMaestro ? 🙂

**Comment by diegocr** [comment]
Actually, @lazarljubenovic, i think we should be reporting this in https://github.com/DmitrySoshnikov/regexp-tree (?)
